# Generated by Django 2.1.5 on 2019-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_timestamp', models.CharField(default='', max_length=15, null=True)),
                ('sdk_version_code', models.CharField(default='', max_length=10, null=True)),
                ('event_source', models.CharField(default='', max_length=50, null=True)),
                ('event_id', models.CharField(default='', max_length=50, null=True)),
                ('event_type', models.CharField(default='', max_length=50, null=True)),
                ('download_url', models.CharField(default='', max_length=500, null=True)),
                ('apk_package_name', models.CharField(default='', max_length=50, null=True)),
                ('apk_version_code', models.CharField(default='', max_length=10, null=True)),
                ('apk_size', models.CharField(default='', max_length=10, null=True)),
                ('progress', models.CharField(default='', max_length=5, null=True)),
                ('ad_join_id', models.CharField(default='', max_length=20, null=True)),
                ('app_id', models.CharField(default='', max_length=50, null=True)),
                ('h5_extra_data', models.CharField(default='', max_length=100, null=True)),
                ('pause_cause', models.CharField(default='', max_length=20, null=True)),
                ('state', models.CharField(default='', max_length=10, null=True)),
                ('dp_extension', models.CharField(default='', max_length=50, null=True)),
                ('image_url', models.CharField(default='', max_length=100, null=True)),
                ('type', models.CharField(default='', max_length=10, null=True)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
