# Generated by Django 2.1.5 on 2019-02-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_timestamp', models.CharField(default='', max_length=15)),
                ('sdk_version_code', models.CharField(default='', max_length=10)),
                ('download_url', models.CharField(default='', max_length=500)),
                ('apk_package_name', models.CharField(default='', max_length=50)),
                ('apk_version_code', models.CharField(default='', max_length=10)),
                ('apk_size', models.CharField(default='', max_length=10)),
                ('app_id', models.CharField(default='', max_length=50)),
                ('ad_join_id', models.CharField(default='', max_length=20)),
                ('pub_date', models.DateTimeField()),
                ('h5_extra_data', models.CharField(default='', max_length=100)),
                ('pause_cause', models.CharField(default='', max_length=20)),
                ('progress', models.CharField(default='', max_length=5)),
                ('state', models.CharField(default='', max_length=10)),
                ('dp_extension', models.CharField(default='', max_length=50)),
                ('image_url', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
