# Generated by Django 2.1.5 on 2019-02-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadinfo',
            name='ad_join_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='apk_package_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='apk_size',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='apk_version_code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='app_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='client_timestamp',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='download_url',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='dp_extension',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='h5_extra_data',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='image_url',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='pause_cause',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='progress',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='sdk_version_code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='state',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='downloadinfo',
            name='type',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
